---
- hosts: all
  become: yes
  tasks:
  - name: Install base packages
    apt:
      name: ['git','git-extras','wget','curl','tilix','vim','apt-transport-https','ca-certificates','software-properties-common']
      update_cache: yes
      state: latest
  - name: Remove useless packages
    apt: 
      name: ['simple-scan','onboard*','libreoffice*','media-player*','rhythmbox*','vlc*','gimp*','pix*','thunderbird*','hexchat*','transmission*','tomboy']
      state: absent
      autoclean: yes
      autoremove: yes

- hosts: all
  tasks:
  - name: Setup Git
    shell: |
      git alias st status
      git alias ci commit
      git alias co checkout
      git alias lg show-tree
      exit 0
