---
- hosts: all
  become: yes
  tasks:
  - name: Install base packages
    apt:
      name: ['git','git-extras','wget','curl','tilix','vim','apt-transport-https','ca-certificates','software-properties-common','build-essential','libssl-dev','htop','tree','make','libc6-i386','lib32z1','libc6','python','python-pip','python-dev','libssl-dev','libcurl4-gnutls-dev','libexpat1-dev','unzip','python-lxml','g++','asciinema']
      update_cache: yes
      state: latest

- hosts: all
  tasks:
  - name: Install SDKMan
    shell: curl -s "https://get.sdkman.io" | bash
    args:
      warn: false
  - name: Install SDKMan
    shell: |
      cd "{{ ansible_env.HOME }}/.sdkman/bin/"
      source ./sdkman-init.sh
      sdk install java
      cd
      exit 0
  - name: Install NVM
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      warn: false
  - name: Install Node
    shell: |
      #cd $NVM_DIR
      #pwd > ../titi
      #ls . >> ../titi
      source "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      #command -v nvm >> ../titi
      nvm install node
      exit 0
