---
- hosts: dev
  tasks:
  - name: Copy aliases
    copy:
      src: config/
      dest: "~/.rc/."
  - name: Setup all RCs
    shell: |
      touch ~/.bash_aliases
      nb_definitions=`grep ALIAS ~/.bash_aliases | wc -l`
      if [ $nb_definitions -eq 0 ]; then
        echo "for ALIAS in \`(ls -a ~/.rc)\`; do" > ~/.bash_aliases
        echo "if [[ -f ~/.rc/\$ALIAS ]]; then source ~/.rc/\$ALIAS; fi" >> ~/.bash_aliases
        echo "done" >> ~/.bash_aliases
      fi
      exit 0
  - name: Define global gitignore 
    copy:
      src: .gitignore
      dest: "~/.gitignore"
  - name: Setup Git global ignore
    shell: git config --global --replace-all core.excludesfile '~/.gitignore'
  - name: Setup git aliases
    shell: |
      if [ -f ~/.gitconfig ]; then
        nb_definitions=`grep show-tree ~/.gitconfig | wc -l`
        if [ $nb_definitions -eq 0 ]; then
          cat ~/.rc/git/aliases >> ~/.gitconfig
        fi
      fi
      exit 0
  - name: Create ssh-keygen if it does not already exist
    shell: |
      if [ ! -f ~/.ssh/id_rsa ]; then
        ssh-keygen -f id_rsa -t rsa -q   -N "''"
      fi
      exit 0
    args:
      executable: /bin/bash
  - name: Check if kube-ps1 is already downloaded
    shell: echo `ls ~/.rc/prompts | grep kube-ps1`
    register: kubeps1
  - name: Download Kube-ps1 prompt
    git:
      repo: 'https://github.com/jonmosco/kube-ps1.git'
      dest: ~/.rc/prompts/kube-ps1
    when: kubeps1.stdout == ""
  # Alternate prompts
  - name: Check if bash-git-prompt is already downloaded
    shell: echo `ls ~/.rc/prompts | grep bash-git-prompt`
    register: bashgitprompt
  - name: Download git prompt
    git:
      repo: 'https://github.com/OlivierDupre/bash-git-prompt.git'
      dest: ~/.rc/prompts/bash-git-prompt
    when: bashgitprompt.stdout == ""
  # - name: Define gitprompt options
  #   copy:
  #     src: prompt/gitprompt
  #     dest: "~/.rc/prompts/bash-git-prompt/custom-gitprompt.sh"
  # - name: Download Polyglot prompt
  #   git:
  #     repo: 'https://github.com/agkozak/polyglot.git'
  #     dest: ~/.rc/prompts/polyglot
  # - name: Download Polyglot-Kube-ps1 prompt
  #   git:
  #     repo: 'https://github.com/agkozak/polyglot-kube-ps1.git'
  #     dest: ~/prompt/polyglot-kube-ps1
  # - name: Add current user to VBox group to provide access to shared folders
  #   shell: adduser $SUDO_USER vboxsf