---
- hosts: all
  become: yes
  tasks:
  - name: Install base packages
    apt:
      name: ['git','git-extras','wget','curl','tilix','vim','apt-transport-https','ca-certificates','software-properties-common','build-essential','libssl-dev','htop','tree','make','libc6-i386','lib32z1','libc6','python','python-pip','python-dev','libssl-dev','libcurl4-gnutls-dev','libexpat1-dev','unzip','python-lxml','g++','asciinema','gnupg-agent','snapd']
      update_cache: yes
      state: latest

- hosts: all
  tasks:
  - name: Install SDKMan
    shell: curl -s "https://get.sdkman.io" | bash
    args:
      warn: false
  - name: Install SDKMan
    shell: |
      cd "{{ ansible_env.HOME }}/.sdkman/bin/"
      source ./sdkman-init.sh
      sdk install java
      cd
      exit 0
  - name: Install NVM
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      warn: false
  - name: Install Node
    shell: |
      source "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      nvm install node
      exit 0

- hosts: master
  become: yes
  tasks:
  - name: Install VSCode
    shell: snap install vscode --classic
    # Load config with extension Settings Sync. Github token store separated, privately in notes with Gist Id.
    

