---
- hosts: all
  become: yes
  tasks:
  - name: Install base packages
    apt:
      name: ['git','git-extras','wget','curl','tilix','vim','apt-transport-https','ca-certificates','software-properties-common']
      update_cache: yes
      state: latest
  - name: Remove useless packages
    apt: 
      name: ['simple-scan','onboard*','libreoffice*','media-player*','rhythmbox*','vlc*','gimp*','pix*','thunderbird*','hexchat*','transmission*','tomboy']
      state: absent
