---
- hosts: all
  become: yes
  tasks:
  - name: Remove docker packages
    apt: 
      name: ['docker','docker-engine','docker.io','containerd','runc']
      state: absent
  - name: Install Docker
    shell: snap install docker
  - name: Save logname as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Define Docker daemon options
    # Read options from https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
    template:
      # For snap installation of Docker. https://github.com/docker/docker-snap/issues/22#issuecomment-423361607
      src: daemon-template.json
      dest: /var/snap/docker/current/config/daemon.json
  - name: Restart Docker to take into account new config
    shell: snap restart docker
    
      