---
- hosts: dev
  become: yes
  vars:
    config_folder: "/etc/docker"
  tasks:
  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Backup original config file
    copy:
      src: "{{ config_folder }}/daemon.json"
      dest: "{{ config_folder }}/daemon.json.bkp"
  - name: Define Docker daemon options
    # Read options from https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
    template:
      src: daemon-template.json
      dest: "{{ config_folder }}/daemon.json"
  - name: Reload docker service config
    shell: systemctl daemon-reload 
  - name: Restart docker service
    shell: systemctl restart docker
# Optionnally, run these to add run Docker without sudo. This is dangerous and it's highly recommended NOT to do this.
  # groupadd docker
  # usermod -aG docker $USER
