---
- hosts: all
  become: yes
  tasks:
  - name: Remove docker packages
    apt: 
      name: ['docker','docker-engine','docker.io','containerd','runc']
      state: absent
  - name: Remove Docker snaps
    shell: snap remove docker
  - name: Install Docker
    shell: snap install docker --channel=edge
  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Define Docker daemon options
    # Read options from https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
    template:
      # For snap installation of Docker. https://github.com/docker/docker-snap/issues/22#issuecomment-423361607
      # Default data-root is set to "data-root": "/var/snap/docker/common/var-lib-docker" with a flag on the daemon
      # vi usr/sbin/invoke-rc.d usr/sbin/update-rc.d snap/manifest.yaml snap/snapcraft.yaml meta/hooks/install meta/hooks/post-refresh
      src: daemon-template.json
      dest: /var/snap/docker/current/config/daemon.json
  - name: Restart Docker to take into account new config
    shell: snap restart docker
    
      