---
- hosts: all
  become: yes
  tasks:
  - name: Remove docker packages
    apt: 
      name: ['docker','docker-engine','docker.io','containerd','runc']
      state: absent
  - name: Install base packages for Docker
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common']
      update_cache: yes
      state: latest
  - name: Retrieve offical Docker GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    args:
      warn: false
  - name: Find Ubuntu codename
    shell: . /etc/os-release ; echo $UBUNTU_CODENAME
    register: ubuntu_codename
    ignore_errors: true
  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout_lines[0] }} stable"
      state: present

