---
- hosts: all
  become: yes
  vars:
    docker_version: "18.06.0~ce~3-0~ubuntu"
  tasks:
  - name: Remove docker packages
    apt: 
      name: ['docker','docker-ce','docker-engine','docker.io','containerd','runc','containerd.io', 'docker-ce-cli']
      state: absent
  - name: Remove Docker snaps
    shell: snap remove docker
  - name: Install base packages for Docker
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common']
      update_cache: yes
      state: latest
  - name: Retrieve offical Docker GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    args:
      warn: false
  - name: Find Ubuntu codename
    shell: . /etc/os-release ; echo $UBUNTU_CODENAME
    register: ubuntu_codename
    ignore_errors: true
  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout_lines[0] }} stable"
      state: present
  - name: Install Docker
    apt:
      # https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1
      #name: docker-ce={{ docker_version }}
      name: docker-ce
      update_cache: yes

  - name: Define Docker daemon options
    # Read options from https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
    template:
      src: daemon-template.json
      dest: /etc/docker/daemon.json
  - name: Reload docker service config
    shell: systemctl daemon-reload 
  - name: Restart docker service
    shell: systemctl restart docker 