---
- hosts: master
  become: yes
  tasks:
    # https://medium.com/@Alibaba_Cloud/how-to-install-and-deploy-kubernetes-on-ubuntu-16-04-6769fd1646db
  - name: Add K8S repository signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present 
  - name: Add K8S repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: Install kubelet & kubeadm
    apt:
      name: ['kubelet','kubeadm']
      state: latest
      update_cache: yes
  - name: Setup K8S cluster
    shell: |
      kubeadm init --pod-network-cidr=192.168.56.101/24
      exit 0
    register: output
  - debug: var=output.stdout_lines

  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Save kubeadm output
    shell: echo {{ output.stdout_lines }} >> {{ logname_home }}/.kubeadm.init
