---
- hosts: master
  become: yes
  tasks:
  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Delete K8S cluster
    shell: |
      kubeadm reset -f;
      rm -Rf "{{ logname_home.stdout }}/.kube/*";
      exit 0
    register: output
  - debug: 
      msg="{{ hostvars[item]["groups"]["master"][0] }}" 
    with_items: "{{ groups['master'] }}"
  - name: Setup K8S cluster
    shell: |
      kubeadm init --pod-network-cidr=192.168.56.0/24;
      exit 0
    register: output
  - debug: var=output.stdout_lines

  - name: Save kubeadm output
    shell: echo "{{ output.stdout_lines }}" > "{{ logname_home.stdout }}"/.kube/init.log
  - name: Setup K8S config
    shell: |
      cp -i /etc/kubernetes/admin.conf "{{ logname_home.stdout }}/.kube/config";
      chown -R $SUDO_USER:$SUDO_USER "{{ logname_home.stdout }}/.kube";
      exit 0