---
- hosts: master
  become: yes
  tasks:
  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Save join nodes command
    shell: >
      kubeadm token create --print-join-command > "{{ logname_home.stdout }}/.kube/join.sh";
      chown $SUDO_USER:$SUDO_USER "{{ logname_home.stdout }}/.kube/join.sh";
      chmod u+x "{{ logname_home.stdout }}/.kube/join.sh";
      exit 0
  - name: Save Join script path
    set_fact: join_script_path="{{ logname_home.stdout }}/.kube/join.sh"

- hosts: nodes
  become: yes
  tasks:
    - debug: 
        msg="{{ hostvars[item]['join_script_path'] }}"
      with_items: "{{ groups['master'] }}"

    - name: Join nodes to master
      script: "{{ hostvars[item]['join_script_path'] }}"
      with_items: "{{ groups['master'] }}"