---
- hosts: all
  become: yes
  tasks:
  - name: Disable swap as it is mandatory for K8S installation
    shell: >
      sed -i.bak '/swapfile/d' /etc/fstab;
      swapoff -a;
      exit
    # https://medium.com/@Alibaba_Cloud/how-to-install-and-deploy-kubernetes-on-ubuntu-16-04-6769fd1646db
  - name: Save logname (aka user) home as a variable
    # https://stackoverflow.com/a/7359006
    shell: > 
      echo $(getent passwd $SUDO_USER | cut -d: -f6)
    register: logname_home
  - name: Add K8S repository signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present 
  - name: Add K8S repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: Create folder for K8S config
    file:
      path: "{{ logname_home.stdout }}/.kube"
      state: directory
      mode: 0755
  - name: Add K8S aliases
    copy:
      src: k8s_aliases
      dest: "{{ logname_home.stdout }}/.k8s_aliases"
  - name: Load K8S aliases
    shell: |
      nb_definitions=`grep k8s_aliases ~/.bash_aliases | wc -l`
      if [ $nb_definitions -eq 0 ]; then
        echo "if [ -f ~/.k8s_aliases ]; then"  >> ~/.bash_aliases
        echo "  . ~/.k8s_aliases"  >> ~/.bash_aliases
        echo "fi"  >> ~/.bash_aliases
      fi
      exit 0