---
- hosts: dev
  become: yes
  vars:
    config_folder: "/etc/kata-containers"
    kata_container_folder: "/snap/kata-containers/current/usr/share/defaults/kata-containers"
  tasks:
  - name: Install kata-container as a snap
    shell: snap install kata-containers --classic
  - name: Create folder to put kata-container config
    file: 
      path: "{{ config_folder }}"
      state: directory
      mode: 0755
  - name: Copy kata-container config and make it editable
    copy:
      src: "{{ kata_container_folder }}/configuration.toml"
      dest: "{{ config_folder }}"