---
- hosts: dev
  become: yes
  tasks:
  - name: Download Openshift CLI
    get_url:  # https://www.okd.io/download.html
      url: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
      dest: /tmp
  - name: Extract Openshift CLI
    unarchive:
      src: /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
      dest: /tmp
  - name: Copy Openshift CLI to /usr/bin
    copy:
      src: /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc
      dest: /tmp/oc
      mode: '0755'
