---
- hosts: all
  become: yes
  tasks:
  - name: Install personal packages
    apt:
      name: ['most','asunder','pdfsam','flac','gparted','openshot','timeshift','playonlinux','gettext','colordiff','meld','toilet','cmatrix','asciinema','snapd']
      update_cache: yes
      state: latest
  - name: Install Spotify
    shell: |
      snap install spotify whatsdesk slack chromium tor
      snap install skype --classic
      snap install slack --classic