---
- hosts: all
  become: yes
  tasks:
  - name: Remove useless packages
    apt: 
      name: ['simple-scan','onboard*','libreoffice*','media-player*','rhythmbox*','vlc*','gimp*','pix*','thunderbird*','hexchat*','transmission*','tomboy','cmatrix','imagemagick','inkscape','openshot',blender','asunder','imagemagic*']
      state: absent
      autoclean: yes
      autoremove: yes