---
- hosts: all
  become: yes
  tasks:
  - name: Remove useless packages
    apt: 
      name: ['simple-scan','onboard*','libreoffice*','media-player*','rhythmbox*','vlc*','gimp*','pix*','thunderbird*','hexchat*','transmission*','tomboy']
      state: absent
      autoclean: yes
      autoremove: yes
